# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/redding/ggem/ruby-2.3.7
    docker:
       - image: circleci/ruby:2.3.7
    steps:
      - checkout
      - restore_cache:
          keys:
          - ruby-2.3.7-dependencies
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: ruby-2.3.7-dependencies
      - run:
          name: run Assert test suite
          command: |
            mkdir /tmp/test-results
            bundle exec assert
